config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    resources :tweets do 
      post :follower
      resources :likes
       member do
        post 'retweet'
    end
  end

  namespace :api do
    resources :tweets
  end

  devise_scope :user do
    post 'follow/:id', to: 'friends#follow', as: 'follow_user'
    delete 'follow/:id', to: 'friends#unfollow', as: 'unfollow_user'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    } 

  root "tweets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/api/news', to: 'api/apis#index'
  post '/api/create', to: 'api/apis#create'
  get "/api/:date1/:date2", to: "api/apis#date"
  get 'search', to: 'search#index'
  get 'friends', to: 'friends#index'

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include ActionView::Helpers::UrlHelper
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :tweet_hash_tags
    has_many :hash_tags, through: :tweet_hash_tags
    validates :content, presence: true
    after_commit :create_hash_tags, on: :create

    def retweet_ref
        Tweet.find(self.rt_ref)
    end

    def create_hash_tags
        extract_name_hash_tags.each do |name|
          hash_tags.create(name: name)
        end
    end
      
    def extract_name_hash_tags
        content.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
    end

    def tweets(user)

    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy retweet]

  # GET /tweets or /tweets.json
  def index
    @q = Tweet.ransack(params[:q])
    @tweet = Tweet.new
    #if signed_in?
      #@tweets = User.tweets_for_me(current_user).page(params[:page]).per(50)
    #else
      @tweets = @q.result(distinct: true).order("created_at DESC").page(params[:page]).per(50)
    #end
  end

  def retweet
    redirect_to root_path, alert: 'it is not possible to retweet' and return if @tweet.user == current_user
    retweeted = Tweet.new(content: @tweet.content)
    retweeted.user = current_user
    retweeted.rt_ref = @tweet.id
    if retweeted.save
      if @tweet.retweet.nil?
        @tweet.update(retweet: @tweet.retweet = 1)  
      else
        
        @tweet.update(retweet: @tweet.retweet += 1)
      end
      
      redirect_to root_path, notice: 'successfully entered'
    else
      redirect_to root_path, alert: 'it is not possible to retweet'
    end 
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    
  end
  
  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card text-center mx-auto col-md-6 mb-3">
        <h3 class="card-title py-3">Created New Tweet</h3>
        <div class="form-group">
            <%= form.text_area(:content, rows: 3, class: 'col-md-7') %>
        </div>
        <div class="actions my-2">
          <%= form.submit "Created New Tweet", :class => 'btn btn-primary' %>
        </div>
    </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
  <%= render 'form', tweet: @tweet %>
<%end%> 
<div class="container" >
  <h1 style="color:blue">Tweets<i class="fab fa-twitter"></i></h1>
  <%= search_form_for @q do |f| %>
    <div class="field">
      <%= f.label :content_cont, "Search: "%>
      <%= f.search_field :content_cont %>
    </div>
    <div class="actions"><%= f.submit "Search" %></div>
  <% end %>
  <% @tweets.each do |tweet| %>
    <div style="border: PowderBlue 2px solid;border-radius: 20px; padding: 20px; ">
      <div align="left" >
        <img src="<%= tweet.user&.user_photo %>" width="60" height="60" class="rounded-circle mb-2" >
        <b><%= tweet.user&.user_name %></b>
      </div>

      <div align="left", top: 50px;>
          <% tweet.content.to_s.split(' ').each do |word| %>
          <% if word.start_with?('#') %>
            <%= link_to word, search_path(query: word) %>
          <%else %>
            <%= word %>
          <%end %>
        <% end %>
      </div>
      <div align="left" style="margin: 10px 0 ">
        <%= link_to "#{time_ago_in_words(tweet.created_at)} ago", tweet%> |
        <%= link_to 'Show', tweet %> |
        <% if signed_in? && tweet.user == current_user %>
          <%= link_to 'Edit', edit_tweet_path(tweet) %> |
          <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %> |
        <% end %>
        <%= link_to retweet_tweet_path(tweet), data: { confirm: 'Do you want retweet?' }, method: :post  do %> 
          <i class="fas fa-retweet"></i>
        <% end %>
        <%= tweet.retweet %>
        <%= tweet.likes.count %>   
        <% if  user_signed_in?%>
          <% if like(tweet, current_user) %>
            <%= link_to tweet_like_path(tweet, like(tweet, current_user)), method: :delete do %>
              <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to tweet_likes_path(tweet), method: :post  do %>
                <i class="far fa-heart"></i>
            <% end  %>
          <% end %>
        <% end %>
      </div>
      <div align="right" style="margin: 0px 55px 0px">
        <% if !tweet.rt_ref.nil? %>
          <%= link_to "#{tweet.user.user_name} ha retweeteado", tweet.retweet_ref  %>
        <% end %> 
      </div>
      <section id="all-links"  align="left">
        <% if  user_signed_in? %>
          <% if pre_follow(tweet.user) %>
              <h5><%= link_to "Unfollow", unfollow_user_path(tweet.user.id), method: :delete %></h5>
          <% else %>
              <h5><%= link_to "Follow", follow_user_path(tweet.user.id), method: :post  %></h5>
          <% end%>
        <% end%>
      </section>
    </div> 
    
  <% end %>
  <%= paginate @tweets%>
  <%= link_to_next_page @tweets, 'Show More Tweets' %>
  <%= link_to_prev_page @tweets, 'Show Previous Tweets' %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p  id="notice"><%= notice %></p>
<p>
<strong>Photo:</strong>
<img src="<%= @tweet.user.user_photo %>"'width="60" height="60" class="rounded-circle mb-2">
</p>

<p>
<strong>Name:</strong>
<%= @tweet.user.user_name %>
</p>

<p>
<strong>Content:</strong>
<%= @tweet.content %>
</p>


<p>
<strong>Likes:</strong>
    <%@tweet.likes.each do |like| %>
        <ul style="list-style-type:none" >
            <img src="<%= like.user.user_photo %>" class="img-thumbnail rounded-circle" style="max-width: 130px;">
        </ul>        
    <% end %>
</p>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>