config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    resources :tweets do 
      post :follower
      resources :likes
       member do
        post 'retweet'
    end
  end

  namespace :api do
    resources :tweets
  end

  devise_scope :user do
    post 'follow/:id', to: 'friends#follow', as: 'follow_user'
    delete 'follow/:id', to: 'friends#unfollow', as: 'unfollow_user'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    } 

  root "tweets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/api/news', to: 'api/apis#index'
  post '/api/create', to: 'api/apis#create'
  get "/api/:date1/:date2", to: "api/apis#date"
  get 'search', to: 'search#index'
  get 'friends', to: 'friends#index'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #1DA1F2">
    <div class="my-auto mx-4">
        <a class="navbar-brand text-white" href="<%=root_path %>">Twitter<i class="fab fa-twitter"></i></a>
    </div>
    <ul class="navbar-nav">
            <% if user_signed_in? %>
            <li><%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary mx-4'  %></li>
        <% else %>
            
            <li><%= button_to 'Ingresar', new_user_session_path, :class => 'btn btn-primary mx-4' %></li>
            <li><%= button_to 'Registrarse', new_user_registration_path, method: :get, :class => 'btn btn-primary mx-4' %></li>
            <li><%= button_to 'Mis Amigos', friends_path, method: :get, :class => 'btn btn-primary mx-4' %></li>
             <li><%= button_to 'Mi Perfil', edit_user_registration_path, method: :get, :class => 'btn btn-primary mx-4' %></li>
        <% end %>
    </ul>
    <% if user_signed_in?  %>
        <div class="container-fluid">
            <b><p style="color:black" >Bienvenido/a: <%= current_user.user_name %><img src="<%= current_user.user_photo %>" width="40" height="40" class="rounded-circle mb-2" ></p></b>
        </div>
    <%end%>
    
</nav>